spring:
  datasource:
      url: jdbc:mysql://localhost:3306/super_market?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: super_market
      password: 123454321
  mvc:
    static-path-pattern: /image/**
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  web:
    resources:
      static-locations: file:D:/HTML+CSS+JavaScript/vue/project/recommendation/img/
  config:
    activate:
      on-profile: local
server:
  port: 8091
logging:
  config: classpath:logback-local.xml
baseUrl:
  os:
    windows:
      root: "D:/HTML+CSS+JavaScript/market/"
      image: "D:/HTML+CSS+JavaScript/market/img/"
      video: "D:/HTML+CSS+JavaScript/market/video/"
      file: "D:/HTML+CSS+JavaScript/market/file/"
    linux:
      root: "/www/wwwroot/information/res/"
      image: "/www/wwwroot/information/res/img/"
      video: "/www/wwwroot/information/res/video/"
      file: "/www/wwwroot/information/res/file/"